#!/bin/sh
### BEGIN INIT INFO
# Provides:          <NAME>
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       <DESCRIPTION>

# paste the script into a file elasticsearch in /etc/init.d and changing the values of JAVA_HOME, PIDFILE and LOGFILE 
# if you face any permission denied with /var/log/elasticsearch.log while running the script give full permissions to the same file
# If you are working with Elastic-search update /etc/sysctl.conf with value vm.max_map_count = 262144
# after all this do update-rc.d elasticsearch defaluts

### END INIT INFO
PATH=$PATH:$HOME/.local/bin:$HOME/bin
export JAVA_HOME=/opt/jdk-10.0.2
export PATH=$PATH:$JAVA_HOME/bin
export PATH


SCRIPT=/srv/db2/data1/elasticsearch/bin/elasticsearch
RUNAS=elasticsearch

PIDFILE=/var/run/elasticsearch/elasticsearch.pid
LOGFILE=/var/run/elasticsearch/elasticsearch.log

start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

uninstall() {
  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
  local SURE
  read SURE
  if [ "$SURE" = "yes" ]; then
    stop
    rm -f "$PIDFILE"
    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
    update-rc.d -f <NAME> remove
    rm -fv "$0"
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  uninstall)
    uninstall
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|uninstall}"
esac
